### ISSUE TITLE
Allow to disable Jolokia and Prometheus

### ISSUE THREAD

**Issue by cdprete** [eclipse/jkube#1294]
Hi.
I'm using the versio `1.6.0` of the plugin and I'm not able to run multiple containers in the same Pod within a k3s cluster because of port clashing. In particular, on the second container starting I've:
```
$ kubectl logs -f deploy/app-backend-deployment -n app-services -c backend
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
INFO exec  java -javaagent:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -javaagent:/usr/share/java/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=9779:/opt/jboss/container/prometheus/etc/jmx-exporter-config.yaml -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/app-backend-1.0.0-SNAPSHOT.jar
Could not start Jolokia agent: java.lang.IllegalStateException: Cannot open keystore for https communication: java.net.BindException: Address already in use
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:555)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
        at jdk.httpserver/sun.net.httpserver.ServerImpl.bind(ServerImpl.java:134)
        at jdk.httpserver/sun.net.httpserver.HttpServerImpl.bind(HttpServerImpl.java:54)
        at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer.<init>(HTTPServer.java:145)
        at io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:31)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3cf9ef7e91, pid=1, tid=154
#
# JRE version: OpenJDK Runtime Environment 21.9 (17.0.1+12) (build 17.0.1+12-LTS)
# Java VM: OpenJDK 64-Bit Server VM 21.9 (17.0.1+12-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, serial gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x21e91]  abort+0x203
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /deployments/hs_err_pid1.log
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%208&component=java-17-openjdk
#
```
The ports used for the Jolokia as well as Prometheus agent seem to be quite hardcoded, therefore both the containers (2 Spring Boot applications) get the same ports and they clash.
Following the docs, I've tried setting the `jolokiaPort` and `prometheusPort`  to `0` but it didn't really help.
I've tried other base images (like the JDK 17 minimal - which crashes with something like "the working directory is not mounted", or the RedHat UBI image) and I've tried as well to build the image "manually" with the following configuration
```xml
<configuration>
                                <images>
                                    <image>
                                        <name>${docker.qualified-image-name}</name>
                                        <registry>${docker.repository-name}</registry>
                                        <build>
                                            <optimise>true</optimise>
                                            <tags>
                                                <tag>latest</tag>
                                                <tag>${project.version}</tag>
                                            </tags>
                                            <from>registry.access.redhat.com/ubi8/openjdk-${java.version}-runtime</from>
                                            <entryPoint>
                                                <shell>java -jar /opt/demo/${project.build.finalName}.jar</shell>
                                            </entryPoint>
                                            <assembly>
                                                <mode>dir</mode>
                                                <targetDir>/home/jboss</targetDir>
                                            </assembly>
                                        </build>
                                    </image>
                                </images>
                            </configuration>
```
No luck, of course.

It would be ideal if these agents could be, somehow, disabled if they're not really needed.
Or, in case of multiple containers in the same Pod, they should be able to detect it and pick some other free port (probably it's more complicated to implement).

**Comment by manusa** [comment]
Hi,

I think you tried lots of things that might be unrelated with one and other.

When providing a manual configuration, no Jolokia or Prometheus port should be added. However, your manual image configuration seems to be missing part of the assembly to make it work.

When relying on our base image (any of the standard Generators: Spring Boot, Quarkus, etc.), then yes, those ports are added automatically. However, you should be able to disable them.

> Following the docs, I've tried setting the jolokiaPort and prometheusPort to 0 but it didn't really help.

You should be able to disable them by setting them to 0. How are you doing this? (I think that this is the root of your problem)

**Comment by cdprete** [comment]
Hi @manusa.
Setting the `jolokiaPort` and `prometheusPort` correctly un-expose them (aka, the Dockerfile which is generated doesn't list them in the `EXPOSE` command), but they're still referenced (at least the Prometheus one) by the `run-java.sh` script used by the entrypoint and that's the issue in my opinion.

**Comment by manusa** [comment]
OK, I think I'm understanding better now.

I understand that you're talking about our base image: https://quay.io/repository/jkube/jkube-java

In this case, we should probably automatically add the `AB_PROMETHEUS_OFF` variable in case `prometheusPort` is disabled (same for `AB_JOLOKIA_OFF`).

**Comment by cdprete** [comment]
Yes, I think it would help. Or, even better, don't add at all Prometheus and/or Jolokia as agents when running the container.
Also, if I may, setting the port to 0 is not very natural in my opinion. I would add some `prometheusEnabled` and `jolokiaEnabled` flags in the configuration.

Of course, for backward compatibility, if the port is 0 then such flags should be set to `false`.
