### ISSUE TITLE
Shutting down JKube remote dev is crashing

### ISSUE THREAD

**Issue by sunix** [eclipse/jkube#2004]
### Describe the bug

Shutting down (Ctrl-C) the remote-dev is crashing. The cluster is not set back to the normal state.

### Eclipse JKube version

1.10.0

### Component

Kubernetes Maven Plugin

### Apache Maven version

other (please specify in additional context)

### Gradle version

None

### Steps to reproduce

1. Follow the https://github.com/marcnuri-demo/jkube-remote-dev#remote-dev-demo-walk-through demo walk-through to the step `Stop the remote-dev by typing Ctrl-c in the terminal where it has been started`
2. Hitting `Ctrl-C`, the exception is raised:
    ```
    [INFO] Server announced support for publickey-hostbound@openssh.com version 0
    [INFO] k8s: Kubernetes Service northwind-db:5432 is now available at local port 5432
    [INFO] k8s: Kubernetes Service rabbit-mq:5672 is now available at local port 15672
    [INFO] k8s: Local port '8080' is now available as a Kubernetes Service at northwind:8080
    ^C[Exception in thread "Thread-2" java.lang.NumberFormatException: For input string: "0m"
    	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
    	at java.base/java.lang.Integer.parseInt(Integer.java:668)
    	at java.base/java.lang.Integer.valueOf(Integer.java:999)
    	at org.fusesource.jansi.io.AnsiOutputStream.write(AnsiOutputStream.java:199)
    	at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:137)
    	at java.base/java.io.PrintStream.write(PrintStream.java:568)
    	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
    	at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:313)
    	at java.base/sun.nio.cs.StreamEncoder.flushBuffer(StreamEncoder.java:111)
    	at java.base/java.io.OutputStreamWriter.flushBuffer(OutputStreamWriter.java:178)
    	at java.base/java.io.PrintStream.write(PrintStream.java:699)
    	at java.base/java.io.PrintStream.print(PrintStream.java:863)
    	at java.base/java.io.PrintStream.println(PrintStream.java:1031)
    	at org.slf4j.impl.SimpleLogger.write(SimpleLogger.java:341)
    	at org.slf4j.impl.SimpleLogger.log(SimpleLogger.java:310)
    	at org.slf4j.impl.SimpleLogger.info(SimpleLogger.java:504)
    	at org.apache.maven.cli.logging.Slf4jLogger.info(Slf4jLogger.java:59)
    	at org.apache.maven.monitor.logging.DefaultLog.info(DefaultLog.java:68)
    	at org.eclipse.jkube.kit.common.util.AnsiLogger.info(AnsiLogger.java:98)
    	at org.eclipse.jkube.kit.remotedev.RemoteDevelopmentService.stop(RemoteDevelopmentService.java:56)
    	at org.eclipse.jkube.maven.plugin.mojo.develop.RemoteDevMojo.lambda$executeInternal$0(RemoteDevMojo.java:46)
    	at java.base/java.lang.Thread.run(Thread.java:833)
    ```

### Expected behavior

1. It should stop properly with no errors.
2. It should tell the user how to restore the state manually.

### Runtime

OpenShift

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Dev Sandbox (workspaces.openshift.com)

**Comment by manusa** [comment]
https://github.com/fusesource/jansi/issues/110
