### ISSUE TITLE
JavaExecGeneratorTest.customize_whenInvoked_shouldNotAddBuildTimestampToBuildDateLabel fails in Java 8

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2409]
## Description

https://ci.eclipse.org/jkube/job/ReleasePipelines/job/ReleaseSnapshots/107/consoleFull

```
java.lang.ExceptionInInitializerError
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.eclipse.jkube.generator.javaexec.JavaExecGeneratorTest.customize_whenInvoked_shouldNotAddBuildTimestampToBuildDateLabel(JavaExecGeneratorTest.java:157)
Caused by: java.lang.NullPointerException: localDateTime
	at java.base/java.time.ZonedDateTime.ofLocal(ZonedDateTime.java:369)
	at java.base/java.time.ZonedDateTime.of(ZonedDateTime.java:342)
	... 2 more
```

Relates to: #2398 / #2393

**Comment by rohanKanojia** [comment]
On pull request checks, I see  [java 8](https://ci.eclipse.org/jkube/job/Build/job/Java8/job/PR-2398/7/consoleFull) check passing. It's using `1.8.0_362` (same as the failing job) .

**Comment by manusa** [comment]
It's the Java distro not the version.
My local environment fails too.

Anyway, it's better to have a way to specifically set the build date. This (#2410) is a much proper way to configure the build plus helps testing stuff without the need for special mocks.
