### ISSUE TITLE
Improve Vert.x support (Generator + Enricher)

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#584]
### Description

Current [Vert.x support implementation](https://github.com/eclipse/jkube/tree/2bee3f27c4a7d93fceaafdb3fc1ad8b176ab38a6/jkube-kit/jkube-kit-vertx) works with `io.reactiverse` [Vert.x Maven Plugin](https://github.com/reactiverse/vertx-maven-plugin), or with Vanilla Vert.x < 4.

However, when creating a Vert.x application from https://start.vertx.io/ and deploying to Kubernetes, the following error is received:
```
SEVERE: Failed to create the vert.x instance
java.lang.IllegalStateException: Failed to create cache dir: /tmp-bf04be10-bf2a-455f-b49b-c133796d22b2
at io.vertx.core.file.impl.FileCache.setupCacheDir(FileCache.java:59)
at io.vertx.core.file.impl.FileCache.setupCache(FileCache.java:29)
at io.vertx.core.file.impl.FileResolver.(FileResolver.java:65)
at io.vertx.core.impl.VertxFactory.createFileResolver(VertxFactory.java:164)
at io.vertx.core.impl.VertxFactory.vertx(VertxFactory.java:78)
at io.vertx.core.Vertx.vertx(Vertx.java:86)
```

- ~~Apparently, adding the following property `-Dvertx.disableFileCPResolving=true` to the [Java Options](https://github.com/eclipse/jkube/blob/2a29784a27e75052767f3cc986da02c812f9dd96/jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/generator/VertxGenerator.java#L58) [fixes the issue](https://github.com/eclipse-vertx/vert.x/issues/1931).~~

- Modifying the temporary directory location [configuration](https://github.com/eclipse/jkube/blob/2a29784a27e75052767f3cc986da02c812f9dd96/jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/generator/VertxGenerator.java#L58) solves the problem.
  In Vert.x v4 there is no subdirectory created, the configuration is used as a prefix instead `/tmpbf04be10...` as opposed to `/tmp/bf04be10...` which produced the aforementioned issue.
  Changing this configuration to something like `/tmp/vertx-cache` fixes the issue and doesn't break compatibility with v3.
  It will also preserves the Cache ClassPath resolution features

- Port inference is something that could be improved too. Still need to find best approach for Vanilla Vert.x projects.

### Expected behavior

- Quick start project via https://start.vertx.io/ with `Vert.x Web`
- Compile and Deploy:
  ```shell
  $ mvn clean package k8s:build k8s:push k8s:resource k8s:apply
  ```
- Application is deployed successfully

**Comment by manusa** [comment]
As for the port inference, there is not an easy way to infer the exposed ports since in many cases ports are assigned programmatically. 
There's already some sort of integration with [Vert.x Config](https://vertx.io/docs/vertx-config/java/) and [properties files](https://github.com/eclipse/jkube/blob/2c2d5da4a7ac43cb36094b57f9855ebf9f341d3d/jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/generator/VertxPortsExtractor.java) that we may need to revisit in the future.
